### ISSUE TITLE
Error while implementing this module in android as well as in ios

### ISSUE THREAD

**Issue by jayesh006** [hyperloop-modules/ti.admob#3]
I am implementing this module for interstitial ad.While compiling on android i am getting an error as " class is not a keyword in index.js  indside the titanium-admob folder"  appcelerator.

**Comment by hansemannn** [comment]
This module requires modern ES6+ enabled in your tiapp.xml (via `<transpile>true</transpile>`), see [this tiapp.xml](https://github.com/appcelerator/kitchensink-v2/blob/master/tiapp.xml#L19) for reference.

**Comment by jayesh006** [comment]
I am currently using titanium sdk version 7.2.0 and enabled transpile to true but it still showing me a error

**Comment by jayesh006** [comment]
i have tried this module "https://github.com/appcelerator-modules/ti.admob" it works fine for banner ads but i want interstitial ads too in  android and ios can you provide a module with code
